# Set soft-wrap and wrap-at-text-width to true when writing documentation.
theme = "vscode"

[editor]
mouse = false
true-color = true

[editor.auto-pairs]
'(' = ')'
'[' = ']'
'{' = '}'

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[keys.normal]
G = "goto_last_line"

[keys.normal.space]
w = { x = "wclose" }

[keys.normal.C-w]
x = "wclose"
