[[language]]
name = "go"
roots = ["go.mod", "go.work"]
language-servers = ["gopls"]
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "python"
roots = ["ty.toml", "pyproject.toml", "setup.py", "requirements.txt"]
language-servers = ["ty"]
auto-format = true
formatter = { command = "ruff", args = ["format", "-" ] }
